In [2]:
import numpy as np

In [ ]:
def convert_to(a: np.ndarray):
    return np.where(a <= 0, -1, 1)

def convert_back(a: np.ndarray):
    return np.where(a > 0, 1, 0)

In [30]:
def get_binary(width):
    values = []
    for i in range(2**width):
        str_repr = list(np.binary_repr(i, width))
        str_repr = ','.join(str_repr)
        values.append(np.fromstring(str_repr, dtype=int, sep=','))
    return values

In [ ]:
# input -> output
training_set_multiple = [
    (np.array([1, 1, 1]), np.array([0,0])),
    (np.array([0,0,1]), np.array([1,0]))
]

# already converted
model = np.array([[-1, 1], [1, -1], [-1, 1]])



In [5]:
inputs = convert_to(np.array([1, 0, 1]))

In [6]:
result = np.matmul(inputs, model)
convert_back(result)

array([0, 1])

In [ ]:
test_set = get_binary(3)
test_set = [convert_to(test_input) for test_input in test_set]
test_set

[array([-1, -1, -1]),
 array([-1, -1,  1]),
 array([-1,  1, -1]),
 array([-1,  1,  1]),
 array([ 1, -1, -1]),
 array([ 1, -1,  1]),
 array([ 1,  1, -1]),
 array([1, 1, 1])]

In [40]:
# results = []
for test_input in test_set:
    result = np.matmul(test_input, model)
    print(f"\nTI: {convert_back(test_input)}, \nMO: {convert_back(result)}")


TI: [0 0 0], 
MO: [1 0]

TI: [0 0 1], 
MO: [0 1]

TI: [0 1 0], 
MO: [1 0]

TI: [0 1 1], 
MO: [1 0]

TI: [1 0 0], 
MO: [0 1]

TI: [1 0 1], 
MO: [0 1]

TI: [1 1 0], 
MO: [1 0]

TI: [1 1 1], 
MO: [0 1]


In [51]:
def train(training_set: list[tuple[np.ndarray, np.ndarray]]):
    sets = training_set[0]
    inputs, outputs = sets
    model = np.zeros([inputs.size, outputs.size])
    for input, output in training_set:
        # convert inputs / outputs to -1 / 1 form
        input_conv = convert_to(input)
        output_conv = convert_to(output)

        delta_w = np.matmul(input_conv.transpose(), output_conv)
        model = np.add(model,delta_w)

    return model

In [57]:
inputs, outputs = training_set_multiple[0]
inputs.shape
outputs.transpose().shape

(2,)

In [ ]:
model = train(training_set_multiple)

results = []
for test_input in test_set:
    result = np.matmul(test_input, model)
    print(f"\nTI: {convert_back(test_input)}, \nMO: {convert_back(result)}")

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)