In [1]:
import numpy as np

In [2]:
def convert_to(a: np.ndarray):
    return np.where(a <= 0, -1, 1)

def convert_back(a: np.ndarray):
    return np.where(a > 0, 1, 0)

In [3]:
def get_binary(width):
    values = []
    for i in range(2**width):
        str_repr = list(np.binary_repr(i, width))
        str_repr = ','.join(str_repr)
        values.append(np.fromstring(str_repr, dtype=int, sep=','))
    return values

In [ ]:
# input -> output
training_set_multiple = [
    (np.array([1, 1, 1]), np.array([0,0])),
    (np.array([0,0,1]), np.array([1,0]))
]

# already converted
model = np.array([[-1, 1], [1, -1], [-1, 1]])

[[-1  1]
 [ 1 -1]
 [-1  1]]


In [108]:
inputs = convert_to(np.array([1, 0, 1]))

In [107]:
# result = np.matmul(inputs, model)
# convert_back(result)

In [93]:
test_set = get_binary(3)
test_set = [convert_to(test_input) for test_input in test_set]
test_set

[array([-1, -1, -1]),
 array([-1, -1,  1]),
 array([-1,  1, -1]),
 array([-1,  1,  1]),
 array([ 1, -1, -1]),
 array([ 1, -1,  1]),
 array([ 1,  1, -1]),
 array([1, 1, 1])]

In [109]:
# results = []
print(model)
for test_input in test_set:
    result = np.matmul(test_input, model)
    print(f"\nTI: {convert_back(test_input)}, \nMO: {convert_back(result)}")

[[-1  1]
 [ 1 -1]
 [-1  1]]

TI: [0 0 0], 
MO: [1 0]

TI: [0 0 1], 
MO: [0 1]

TI: [0 1 0], 
MO: [1 0]

TI: [0 1 1], 
MO: [1 0]

TI: [1 0 0], 
MO: [0 1]

TI: [1 0 1], 
MO: [0 1]

TI: [1 1 0], 
MO: [1 0]

TI: [1 1 1], 
MO: [0 1]


In [ ]:
def train(training_set: list[tuple[np.ndarray, np.ndarray]]):
    sets = training_set[0]
    inputs, outputs = sets
    model = np.zeros([inputs.size, outputs.size])
    for input, output in training_set:
        # convert inputs / outputs to -1 / 1 form
        # for inputs, reshape (transpose in this case, but somehow transpose won't work)
        input_conv = convert_to(np.reshape(input, shape=(input.size, 1)))
        output_conv = convert_to(np.reshape(output, shape=(1, output.size)))

        delta_w = np.matmul(input_conv, output_conv)
        model = np.add(model,delta_w)

    return model

In [111]:
model = train(training_set_multiple)

results = []
for test_input in test_set:
    result = np.matmul(test_input, model)
    print(f"\nTI: {convert_back(test_input)}, \nMO: {convert_back(result)}")


print(model)


TI: [0 0 0], 
MO: [1 1]

TI: [0 0 1], 
MO: [1 0]

TI: [0 1 0], 
MO: [0 1]

TI: [0 1 1], 
MO: [0 0]

TI: [1 0 0], 
MO: [0 1]

TI: [1 0 1], 
MO: [0 0]

TI: [1 1 0], 
MO: [0 1]

TI: [1 1 1], 
MO: [0 0]
[[-2.  0.]
 [-2.  0.]
 [ 0. -2.]]
